source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NWAAlertController_Example', :exclusive => true do
  pod "NWAAlertController", :path => "../"
end

target 'NWAAlertController_Tests', :exclusive => true do
  pod "NWAAlertController", :path => "../"

  pod 'Quick', :git => 'https://github.com/Quick/Quick.git', :branch => 'swift-2.0'
  pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git', :branch => 'swift-2.0'
end
